<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php if ($block->isPaymentwallPaymentMethod()) :?>
    <div class="checkout-success">
        <h1>
            <p><?= $block->escapeHtml(__('Your order has been received')) ?></p>
        </h1>
        <h2 class="pw-sub_title"><?= $block->escapeHtml(__('Thank you for your purchase!')) ?></h2>
        <p class="pw-email_text"><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>

        <div class="actions-toolbar">
            <div class="primary pw-btn__continue">
                <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
            </div>
        </div>
    </div>
    <script>
        require([
            'Magento_Customer/js/customer-data'
        ], function (customerData) {
            customerData.initStorage();
            var sections = ['cart'];
            customerData.invalidate(sections);
            customerData.reload(sections, true);
        });
    </script>
<?php endif;?>
